# Build and run with:
#
# docker build -t accp -f Dockerfile.dev .
# docker run -v $(pwd):/accp --rm -it accp:latest


FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y openjdk-11-jdk
RUN apt-get install -y lcov
RUN apt-get install -y cmake
RUN apt-get install -y dieharder
RUN apt-get install -y build-essential

RUN mkdir /accp
COPY . /accp
WORKDIR /accp

# run the gradlew script just to install gradle in the image
RUN ./gradlew --no-daemon generateEclipseClasspath

ENTRYPOINT /bin/bash
