# Build and run with:
#
# $ docker build -t accp -f Dockerfile.dev .
# $ docker run -v $(pwd):/accp --rm -it accp:latest
#
# Once in the container's shell, quickly iterate on rebuilding AWS-LC and ACCP
# to re-run a single test with:
#
# $ SINGLE_TEST=com.amazon.corretto.crypto.provider.test.EvpSignatureTest
# $ ./gradlew minimal_clean && ./gradlew single_test -DSINGLE_TEST=${SINGLE_TEST}

FROM public.ecr.aws/ubuntu/ubuntu:20.04_stable

# install corretto JDK
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN curl -s https://apt.corretto.aws/corretto.key | apt-key add -
RUN echo 'deb https://apt.corretto.aws stable main' | tee /etc/apt/sources.list.d/corretto.list
RUN apt-get update
RUN apt-get install -y java-11-amazon-corretto-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto/
RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto/' >> /home/.bashrc

# required dependencies for building/testing
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y cmake
RUN apt-get install -y dieharder
RUN apt-get install -y lcov
RUN apt-get install -y python3-pip
RUN pip3 install gcovr

# developement niceties
RUN apt-get install -y ninja-build
RUN apt-get install -y git

RUN git clone --recurse-submodules https://github.com/corretto/amazon-corretto-crypto-provider.git /accp
WORKDIR /accp

# FIPS extensions
RUN apt-get install -y golang-1.18 perl
RUN ln -s /usr/lib/go-1.18/bin/go /usr/bin/go
RUN ln -s /usr/lib/go-1.18/bin/gofmt /usr/bin/gofmt
RUN ln -s /usr/bin/cmake /usr/bin/cmake3

# run the gradlew script just to install gradle in the image
RUN ./gradlew --no-daemon generateEclipseClasspath

ENTRYPOINT /bin/bash
