// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
package com.amazon.corretto.crypto.provider;

import java.security.PrivateKey;

/** Public utility methods */
public class PublicUtils {
  private PublicUtils() {} // private constructor to prevent instantiation

  private static native byte[] expandMLDSAKeyInternal(byte[] key);

  /**
   * TODO [childw]
   *
   * @param key an ML-DSA public key generated by ACCP
   * @return a byte[] containing the PKCS8-encoded seed private key
   */
  public static byte[] expandMLDSAKey(PrivateKey key) {
    if (key == null || !key.getAlgorithm().startsWith("ML-DSA")) {
      throw new IllegalArgumentException();
    }
    return expandMLDSAKeyInternal(key.getEncoded());
  }

  // TODO [childw] move ext mu utility here
}
