#!/usr/bin/env bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Run the JCA/JCE-relevant subset of the OpenJDK jtreg suite against ACCP.
# See tests/jca-conformance/README.md for the design and the exclusion model.
#
# Scaffolding note (issue #550, branch 1): by default this script runs in
# --smoke mode, which validates the harness wiring (jtreg download, ACCP
# install, exclusion parsing) WITHOUT checking out the multi-hundred-MB OpenJDK
# test tree or running the full suite. Branch 2 populates jtreg-test-roots.txt
# and runs the real suite via --full.

set -euo pipefail

#############################################
# Configuration (pinned versions)
#############################################
# jtreg release used to run the tests. Pin for reproducibility.
JTREG_VERSION="${JTREG_VERSION:-7.4+1}"
JTREG_TARBALL_VERSION="${JTREG_VERSION/+/-}" # 7.4+1 -> 7.4-1 for the artifact name

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORK_DIR="${WORK_DIR:-${REPO_ROOT}/build/jca-conformance}"

MODE="smoke"

usage() {
    cat <<EOF
Usage: $0 [--smoke|--full] [--work-dir DIR]

  --smoke   (default) Validate harness wiring without running the full suite.
  --full    Check out the OpenJDK test tree and run the JCA conformance subset.
  --work-dir DIR  Scratch directory (default: ${WORK_DIR}).

Environment:
  ACCP_JAR        Path to a prebuilt AmazonCorrettoCryptoProvider.jar. If unset,
                  the script builds ACCP from this checkout.
  JTREG_VERSION   jtreg release to use (default: ${JTREG_VERSION}).
  TEST_JAVA_HOME  JDK to test against (default: JAVA_HOME, then \`java\` on PATH).
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --smoke) MODE="smoke"; shift ;;
        --full)  MODE="full";  shift ;;
        --work-dir) WORK_DIR="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

#############################################
# Resolve the JDK under test
#############################################
TEST_JAVA_HOME="${TEST_JAVA_HOME:-${JAVA_HOME:-}}"
if [[ -z "${TEST_JAVA_HOME}" ]]; then
    # Derive from `java` on PATH.
    if ! command -v java >/dev/null 2>&1; then
        echo "ERROR: no JDK found. Set TEST_JAVA_HOME or JAVA_HOME, or put java on PATH." >&2
        exit 1
    fi
    TEST_JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(command -v java)")")")"
fi
JAVA_BIN="${TEST_JAVA_HOME}/bin/java"

# Parse the `version "X..."` line specifically. Filtering by the `version` token
# skips noise some JVMs print first (e.g. "Picked up JAVA_TOOL_OPTIONS: ...").
JDK_MAJOR="$("${JAVA_BIN}" -version 2>&1 | grep -E 'version "[0-9]' | head -1 | sed -E 's/.*version "([0-9]+).*/\1/')"
if ! [[ "${JDK_MAJOR}" =~ ^[0-9]+$ ]]; then
    echo "ERROR: could not parse JDK major version from '${JAVA_BIN} -version'." >&2
    exit 1
fi
if [[ "${JDK_MAJOR}" -lt 17 ]]; then
    echo "ERROR: ACCP JCA conformance requires JDK 17+; detected major version '${JDK_MAJOR}'." >&2
    exit 1
fi
echo "==> JDK under test: major version ${JDK_MAJOR} (${TEST_JAVA_HOME})"

#############################################
# Resolve / build the ACCP jar
#############################################
resolve_accp_jar() {
    if [[ -n "${ACCP_JAR:-}" ]]; then
        if [[ ! -f "${ACCP_JAR}" ]]; then
            echo "ERROR: ACCP_JAR='${ACCP_JAR}' does not exist." >&2
            exit 1
        fi
        echo "${ACCP_JAR}"
        return
    fi
    local built="${REPO_ROOT}/build/cmake/AmazonCorrettoCryptoProvider.jar"
    if [[ ! -f "${built}" ]]; then
        echo "==> Building ACCP (no ACCP_JAR supplied)..." >&2
        ( cd "${REPO_ROOT}" && ./gradlew build -x test ) >&2
    fi
    echo "${built}"
}

#############################################
# Collect exclusion selectors for this JDK
#############################################
collect_exclusions() {
    # Prints the merged, comment-stripped exclusion selectors for this JDK.
    local files=("${SCRIPT_DIR}/exclusions/common.txt" "${SCRIPT_DIR}/exclusions/jdk${JDK_MAJOR}.txt")
    for f in "${files[@]}"; do
        [[ -f "$f" ]] || continue
        grep -vE '^\s*(#|$)' "$f" || true
    done
}

#############################################
# Build the java.security override that installs ACCP first
#############################################
write_accp_security_props() {
    # Emits a java.security fragment that registers ACCP as provider #1, ahead
    # of the JDK default providers. jtreg passes this to the test JVM via
    # -Djava.security.properties=<file> (the single '=' form augments rather
    # than replaces the default security properties).
    local out="$1" accp_jar="$2"
    cat > "${out}" <<EOF
# Generated by run-jtreg.sh: install ACCP ahead of default providers.
security.provider.1=com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider
EOF
    echo "${out}"
}

#############################################
# Download jtreg
#############################################
fetch_jtreg() {
    local dest="${WORK_DIR}/jtreg"
    if [[ -x "${dest}/bin/jtreg" ]]; then
        echo "${dest}"
        return
    fi
    mkdir -p "${WORK_DIR}"
    local url="https://builds.shipilev.net/jtreg/jtreg-${JTREG_TARBALL_VERSION}.tar.gz"
    echo "==> Downloading jtreg ${JTREG_VERSION} from ${url}" >&2
    curl -fsSL "${url}" -o "${WORK_DIR}/jtreg.tar.gz"
    tar -xzf "${WORK_DIR}/jtreg.tar.gz" -C "${WORK_DIR}"
    echo "${dest}"
}

#############################################
# Smoke mode: validate wiring only
#############################################
run_smoke() {
    echo "==> [smoke] Validating harness wiring (no OpenJDK checkout, no test run)."

    local accp_jar; accp_jar="$(resolve_accp_jar)"
    echo "==> [smoke] ACCP jar: ${accp_jar}"

    # 1. ACCP must load and install as provider #1 under the JDK under test.
    write_accp_security_props "${WORK_DIR}/accp.security" "${accp_jar}" >/dev/null

    echo "==> [smoke] Verifying ACCP installs as the highest-priority provider..."
    local src="${WORK_DIR}/AccpSmoke.java"
    cat > "${src}" <<'JAVA'
import java.security.Security;
import java.security.Provider;
public class AccpSmoke {
    public static void main(String[] args) throws Exception {
        Provider p = Security.getProviders()[0];
        String name = p.getName();
        System.out.println("Highest-priority provider: " + name);
        if (!"AmazonCorrettoCryptoProvider".equals(name)) {
            System.err.println("FAIL: expected ACCP to be provider #1, got " + name);
            System.exit(1);
        }
        // Sanity: exercise one overridden SPI.
        java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
        if (!"AmazonCorrettoCryptoProvider".equals(md.getProvider().getName())) {
            System.err.println("FAIL: SHA-256 not served by ACCP: " + md.getProvider().getName());
            System.exit(1);
        }
        System.out.println("OK: ACCP installed and serving SHA-256.");
    }
}
JAVA
    "${JAVA_BIN}" -cp "${accp_jar}" \
        -Djava.security.properties="${WORK_DIR}/accp.security" \
        "${src}"

    # 2. Exclusion files must parse.
    echo "==> [smoke] Parsing exclusion files..."
    local n; n="$(collect_exclusions | wc -l | tr -d ' ')"
    echo "==> [smoke] ${n} exclusion selector(s) for JDK ${JDK_MAJOR}."

    # 3. Test-roots file must exist and be non-empty after comment stripping.
    # grep -c counts matching lines; with -v that is the non-comment, non-blank count.
    local roots; roots="$(grep -cvE '^\s*(#|$)' "${SCRIPT_DIR}/jtreg-test-roots.txt" || true)"
    echo "==> [smoke] ${roots} jtreg test root(s) configured."

    echo "==> [smoke] OK. Harness wiring validated. Use --full to run the suite (branch 2)."
}

#############################################
# Full mode: placeholder until branch 2
#############################################
run_full() {
    echo "ERROR: --full is not implemented yet. It is delivered in branch 2 of issue #550," >&2
    echo "       which checks out the pinned OpenJDK test tree and runs jtreg over" >&2
    echo "       jtreg-test-roots.txt with the exclusion lists applied." >&2
    exit 3
}

mkdir -p "${WORK_DIR}"
case "${MODE}" in
    smoke) run_smoke ;;
    full)  run_full ;;
esac
