name: ACCP macOS CI

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  PACKAGE_NAME: ACCP

jobs:
  macOS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    # Test on Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 11
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh
        ./tests/ci/run_accp_test_integration.sh

    # Test on Corretto 17.
    - name: Set up corretto 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 17
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh
        ./tests/ci/run_accp_test_integration.sh
